#
# Module manifest for module 'PowerShellGetCompat'
#
# Generated by: americks
#
# Generated on: 7/14/2020
#

@{
    RootModule = 'PowerShellGetCompat.psm1'
    ModuleVersion = '1.0.0'
    GUID = '68ec3ec1-55bf-42f8-9add-d224e5c76548'
    Author = 'Microsoft Corporation'
    CompanyName = 'Microsoft Corporation'
    Copyright = '(c) Microsoft Corporation. All rights reserved.'
    Description = 'PowerShellGetCompat is a compatibility module that allows use of PowerShellGet 2.x (and below) cmdlet syntax with PowerShellGet 3.0 (and newer) functionality by making a best effort mapping between the cmdlet interfaces of both versions of the module.'
    PowerShellVersion = '3.0'
    FunctionsToExport = @( 
        "Find-CommandProxy", 
        "Find-DscResourceProxy", 
        "Find-ModuleProxy",
        "Find-RoleCapabilityProxy",
        "Find-ScriptProxy",
        "Get-InstalledModuleProxy",
        "Get-InstalledScriptProxy",
        "Get-PSRepositoryProxy",
        "Install-ModuleProxy",
        "Install-ScriptProxy",
        "Publish-ModuleProxy",
        "Publish-ScriptProxy",
        "Register-PSRepositoryProxy",
        "Save-ModuleProxy",
        "Save-ScriptProxy",
        "Set-PSRepositoryProxy",
        "Uninstall-ModuleProxy",
        "Uninstall-ScriptProxy",
        "Unregister-PSRepositoryProxy",
        "Update-ModuleProxy",
        "Update-ScriptProxy"
    )
    CmdletsToExport = @()
    VariablesToExport = '*'
    AliasesToExport = @(
        "Find-Command", 
        "Find-DscResource", 
        "Find-Module",
        "Find-RoleCapability",
        "Find-Script",
        "Get-InstalledModule",
        "Get-InstalledScript",
        "Get-PSRepository",
        "Install-Module",
        "Install-Script",
        "Publish-Module",
        "Publish-Script",
        "Register-PSRepository",
        "Save-Module",
        "Save-Script",
        "Set-PSRepository",
        "Uninstall-Module",
        "Uninstall-Script",
        "Unregister-PSRepository",
        "Update-Module",
        "Update-Script"
    )

    PrivateData = @{
        PSData = @{
            Tags = @('PackageManagement',
            'PSEdition_Desktop',
            'PSEdition_Core',
            'Linux',
            'Mac',
            'Windows')

            LicenseUri = 'https://github.com/PowerShell/PowerShellGetCompat/blob/master/LICENSE'
            ProjectUri = 'https://github.com/PowerShell/PowerShellGetCompat'
            ReleaseNotes = @'
### 1.0.0
* Initial release

## For full history of release notes see changelog:
https://github.com/PowerShell/PowerShellGetCompat/blob/master/CHANGELOG.md
'@
        }
    }

# HelpInfoURI = ''
}
