#
# Module manifest for module 'CompatPowerShellGet'
#
# Generated by: americks
#
# Generated on: 7/14/2020
#

@{
    RootModule = 'CompatPowerShellGet.psm1'
    ModuleVersion = '1.0.0'
    GUID = '68ec3ec1-55bf-42f8-9add-d224e5c76548'
    Author = 'Microsoft Corporation'
    CompanyName = 'Microsoft Corporation'
    Copyright = '(c) Microsoft Corporation. All rights reserved.'
    Description = 'CompatPowerShellGet is a compatibility module that allows use of PowerShellGet 2.x (and below) cmdlet syntax with PowerShellGet 3.0 (and newer) functionality by making a best effort mapping between the cmdlet interfaces of both versions of the module.'
    PowerShellVersion = '3.0'
    FunctionsToExport = @( 
        "Find-Command", 
        "Find-DscResource", 
        "Find-Module",
        "Find-RoleCapability",
        "Find-Script",
        "Get-InstalledModule",
        "Get-InstalledScript",
        "Get-PSRepository",
        "Install-Module",
        "Install-Script",
        "Publish-Module",
        "Publish-Script",
        "Register-PSRepository",
        "Save-Module",
        "Save-Script",
        "Set-PSRepository",
        "Uninstall-Module",
        "Uninstall-Script",
        "Unregister-PSRepository",
        "Update-Module",
        "Update-Script"
    )
    CmdletsToExport = @()
    VariablesToExport = '*'
    AliasesToExport = @()

    PrivateData = @{
        PSData = @{
            Tags = @('PackageManagement',
            'PSEdition_Desktop',
            'PSEdition_Core',
            'Linux',
            'Mac',
            'Windows')

            # LicenseUri = ''
            # ProjectUri = ''
            ReleaseNotes = ''
        }
    }

# HelpInfoURI = ''
}

