#
# Module manifest for module 'PowerShellGet'
#
# Generated by: americks
#
# Generated on: 7/14/2020
#

@{
    RootModule = 'PowerShellGet.psm1'
    ModuleVersion = '0.9.0'
    GUID = '68ec3ec1-55bf-42f8-9add-d224e5c76548'
    Author = 'Microsoft Corporation'
    CompanyName = 'Microsoft Corporation'
    Copyright = '(c) Microsoft Corporation. All rights reserved.'
    Description = 'PowerShellGet is a compatibility module that allows use of PowerShellGet 2.x (and below) cmdlet syntax with PSResourceGet functionality by making a best effort mapping between the cmdlet interfaces of both versions of the module.'
    PowerShellVersion = '3.0'
    FunctionsToExport = @( 
        "Find-Command", 
        "Find-DscResource", 
        "Find-Module",
        "Find-RoleCapability",
        "Find-Script",
        "Get-InstalledModule",
        "Get-InstalledScript",
        "Get-PSRepository",
        "Install-Module",
        "Install-Script",
        "Publish-Module",
        "Publish-Script",
        "Register-PSRepository",
        "Save-Module",
        "Save-Script",
        "Set-PSRepository",
        "Uninstall-Module",
        "Uninstall-Script",
        "Unregister-PSRepository",
        "Update-Module",
        "Update-Script"
    )
    CmdletsToExport = @()
    VariablesToExport = '*'
    AliasesToExport = @()

    PrivateData = @{
        PSData = @{
            Tags = @('PackageManagement',
            'PSEdition_Desktop',
            'PSEdition_Core',
            'Linux',
            'Mac',
            'Windows')

            LicenseUri = 'https://github.com/PowerShell/PowerShellGet/blob/master/LICENSE'
            ProjectUri = 'https://github.com/PowerShell/PowerShellGet'
            ReleaseNotes = @'
### 0.9.0

### 0.0.4
* Changes
- Update module to be compatible with latest version of PowerShellGet (3.0.21-beta21)

### 0.0.3
* Changes
- Updated reference to PowerShellGet 'Url' parameter to 'Uri' to reflect changes made in PowerShellGet

### 0.0.2
* Bug Fix
- Remove -Force parameter when calling into v3 cmdlets

### 0.0.1
* Initial release

## For full history of release notes see changelog:
https://github.com/PowerShell/PowerShellGet/blob/master/CHANGELOG.md
'@
        }
    }

# HelpInfoURI = ''
}
